# Generated by Django 4.0.6 on 2022-08-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_orderoptiongroup_orderoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='order',
            name='bank',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_num',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
