# Generated by Django 4.0.6 on 2022-08-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_restaurant_consumed_calorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='calorie',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
