# Generated by Django 4.0.6 on 2022-08-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_remove_order_address_remove_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderoptiongroup',
            name='order_menu',
        ),
        migrations.DeleteModel(
            name='OrderOption',
        ),
        migrations.DeleteModel(
            name='OrderOptionGroup',
        ),
    ]
